version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  nodejs-app:
    build:
      context: .
    ports:
      - "1010:3000"
    networks:
      - mynetwork
    depends_on:
      - mongodb

networks:
  mynetwork:
